"""relationships changed

Revision ID: da8a3ad659e3
Revises: edaaea7864ad
Create Date: 2025-05-23 04:27:21.484417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8a3ad659e3'
down_revision = 'edaaea7864ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('user_tasks_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_tasks_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_tasks_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('user_tasks_ibfk_2', 'task', ['task_id'], ['id'])

    # ### end Alembic commands ###
